# Generated by Django 5.2.1 on 2025-07-11 16:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        choices=[
                            ("PYTHON", "python"),
                            ("JAVA", "java"),
                            ("DOTNET", "dotnet"),
                            ("DJANGO", "django"),
                            ("REACT", "react"),
                        ],
                        default="PYTHON",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="register",
            name="address",
            field=models.CharField(default="none-address", max_length=255),
        ),
        migrations.AddField(
            model_name="register",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(16),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AddField(
            model_name="register",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="register",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="register",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="register",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="register",
            name="gender",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="register",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="register",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="register",
            name="mobile_no",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="register",
            name="reg_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="register",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name="register",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.course",
            ),
        ),
    ]
